VIDEOS_DATA = {
    "Jenna Blossoms": {
        "🧘 Méditation guidée": [
            {"id": "6IsOFJ4j8YU", "titre": "Lâcher prise"},
            {"id": "LhoFnTMu_co", "titre": "Affirmations positives du soir"},
            {"id": "AXOqsDHQmes", "titre": "Énergie vitale"},
            {"id": "hvnsKYrSzhY", "titre": "Affirmations positives du matin"},
            {"id": "k_7R4OL4oHY", "titre": "Énergie universelle de l'amour"},
            {"id": "BKiaVjcXrgg", "titre": "Chemin vers l'abondance"},
            {"id": "ssyvTAVzjaA", "titre": "Se rencontrer et s'accepter"},
            {"id": "nh-LtlT26Cc", "titre": "Rechargement énergétique"},
            {"id": "7qWmwvPfd2w", "titre": "Rencontrer son animal totem"},
            {"id": "3umJYk9kqDo", "titre": "Se reconnecter avec moi même"},
            {"id": "ml2LoJiMVyk", "titre": "Partager de l'amour"},
            {"id": "S-Bf_HQGUxU", "titre": "Ancrage"},
            {"id": "qtlZ3BOxL3Q", "titre": "Élever sa vibration et celle de la planète"},
            {"id": "9c-atkXvNhY", "titre": "Méditation du soir pour les enfants"},
            {"id": "IpNlX_BllQA", "titre": "Ouverture du coeur"},
            {"id": "723lwelFRWc", "titre": "Méditation du matin"},
            {"id": "qF_N0xjT8yY", "titre": "Méditation du soir"},
            {"id": "PuqtGvQQUdg", "titre": "Développer votre intuition"}
        ],
        "🎙️ Podcast": [
            {"id": "nD1FQ77w_eA", "titre": "Ces attachements qui volent notre énergie"},
            {"id": "1l9thUF5_j4", "titre": "L’intention de votre âme avant de s’incarner"},
            {"id": "PFSVrZV7-6E", "titre": "Doit-on toujours souffrir pour évoluer ?"},
            {"id": "dNRDAwVz9YQ", "titre": "Repérez vos blessures inconscientes en 1 minute"},
            {"id": "A47OSxWVVqk", "titre": "Votre couple est-il encore aligné avec votre âme ?"},
            {"id": "j4kjpGhzoys", "titre": "Réconcilier l’argent et la spiritualité"},
            {"id": "jrBsCJDa8aI", "titre": "Comment être sûr de prendre la bonne décision ?"},
            {"id": "Kk3MgHv-25c", "titre": "6 Clés pour garder une haute vibration même entouré de négativité"},
            {"id": "sTxEXxY4AZI", "titre": "Quel est votre canal intuitif ?"},
            {"id": "_v4mhYIaIaU", "titre": "Recevez CLAIREMENT les messages de vos guides spirituels (avec Sonia Choquette)"},
            {"id": "hw9AaonIgIk", "titre": "Comment garder la foi dans ce monde si dur ?"},
            {"id": "cFq_t8lJmCM", "titre": "Comment recevoir l’aide des ANGES ? (avec Kathryn Hudson)"},
            {"id": "x_sDx0H1mEA", "titre": "Vouloir (tout) contrôler"},
            {"id": "SmVGNkLz4MA", "titre": "Vivre plus de synchronicités au quotidien"},
            {"id": "HrEdWW4AzSs", "titre": "Mon entourage ne partage pas mon chemin spirituel"},
            {"id": "InaFSSsg3AY", "titre": "Oser se lancer dans un grand changement (et dépasser ses peurs)"},
            {"id": "FI-EM-W5wGU", "titre": "Sortie Hors du Corps : Une Porte Vers l’Au-Delà ?!"},
            {"id": "gKBxFSjbzO0", "titre": "Message urgent des guides sur la période actuelle"},
            {"id": "QloRSKDe41E", "titre": "La liberté de choisir sa vie - la clé de l’épanouissement (avec Laurent Gounelle)"},
            {"id": "XFFGygYu6io", "titre": "Être en meilleure santé grâce à nos pensées"},
            {"id": "Sf4QrYz-eKQ", "titre": "Se libérer de l'auto-sabotage"},
            {"id": "-X4pOBtPWc8", "titre": "Intuition, liberté, authenticité : les clés d’une vie épanouie (avec Safia Ayad)"},
            {"id": "uMZAVtv9II0", "titre": "Apprendre à utiliser les cartes oracle"},
            {"id": "YWYxRFztDu4", "titre": "Savoir faire une pause"},
            {"id": "KELfiUfbMcI", "titre": "La mort n'existe pas (avec Stéphane Allix)"},
            {"id": "AwmTy2Rh5L8", "titre": "Trouver et réaliser sa mission de vie"},
            {"id": "dBLPq_HFq_A", "titre": "Comment lâcher prise avec facilité"},
            {"id": "Re3zpVl6LBs", "titre": "Comment recevoir les cadeaux de la vie"},
            {"id": "b0YT46ZGdF4", "titre": "Envoyer de l'amour pour guérir le monde"},
            {"id": "5tUn5eQdcCU", "titre": "Comment surmonter un deuil ?"},
            {"id": "EEiGfOGLiEQ", "titre": "Comment créer son projet de cœur malgré les difficultés"},
            {"id": "OfMmyzKeb9g", "titre": "Les énergies de 2024"},
            {"id": "vErG_jUCfmw", "titre": "Pourquoi choisit-on sa famille ?"},
            {"id": "FNp6x6B4brk", "titre": "Karma : mode d'emploi (avec Malory Malmasson)"},
            {"id": "RXhU_rD36ZE", "titre": "Pourquoi sommes nous guidés vers certains lieux"},
            {"id": "ZYzOAaGGT74", "titre": "Manifester avec le pouvoir de l'intention"},
            {"id": "De1e7YyRpiU", "titre": "Le changement vibratoire actuel (avec Luc Bodin)"},
            {"id": "i0KElexHJZE", "titre": "Notre mission de vie en 2024"},
            {"id": "ppomRhKOpFw", "titre": "Comment vivre les fortes énergies actuelles ?"},
            {"id": "GtKG-M1Zddo", "titre": "Ce moyen rapide de débloquer son intuition"},
            {"id": "_p2ZX4lrKzc", "titre": "Comment allier productivité et flow ?"},
            {"id": "L8N2GOjLYPA", "titre": "Rencontre vibrante (avec Lilou Macé)"},
            {"id": "TBmLLyk6FGE", "titre": "5 clés pour incarner l'abondance dans votre vie"},
            {"id": "ZI4qbhk3-8k", "titre": "La pensée qui a changé ma vie"},
            {"id": "3yFZxA7wwGA", "titre": "Avoir de l'inspiration au quotidien"},
            {"id": "vbPIDXOGZV4", "titre": "Relation à l’Argent : un chemin vers la RÉCONCILIATION du Spirituel et du Matériel (avec Christian Junod)"},
            {"id": "T3LZrusPGSU", "titre": "L'éveil des consciences sur Terre"},
            {"id": "44U5Skeqx0k", "titre": "Mettre en place de nouvelles habitudes"},
            {"id": "K-HDiOUiB0o", "titre": "Renouer avec la Source (avec Stéphane Clément)"},
            {"id": "Y6RVjp_XFoA", "titre": "Comprendre vos défis d'âme"},
            {"id": "IXNtTg0rolo", "titre": "Pourquoi la solitude est si bénéfique"},
            {"id": "NiZEspAIOtM", "titre": "L'amour de soi est-il un acte radical ?"},
            {"id": "kULcCopxO0o", "titre": "Osez faire ce pour quoi vous êtes venu"},
            {"id": "KuHV0b1h0nw", "titre": "L'honnêteté, clé de notre évolution spirituelle"},
            {"id": "Yvg61eqMjxM", "titre": "Comment vivre en alignement ?"},
            {"id": "5SMXdUEK658", "titre": "Comment se sentir légitime dans ce que l'on entreprend ?"},
            {"id": "_1Vl4EX3tDY", "titre": "Êtes-vous un artisan de lumière ?"},
            {"id": "zQUEeJWl1ks", "titre": "Comment voir et comprendre les signes de l'univers ?"},
            {"id": "6H1MAxakQLE", "titre": "Comment vivre une spiritualité incarnée ?"}
        ],
        "✨ Vos chakras": [
            {"id": "FE1oE_CJ-hQ", "titre": "CHAKRA RACINE : s’ancrer et dépasser ses peurs"},
            {"id": "KzZlU1ARQTE", "titre": "CHAKRA SACRÉ : Comment retrouver la JOIE dans sa vie"},
            {"id": "OicBznC46FY", "titre": "CHAKRA DU PLEXUS SOLAIRE : retrouver son pouvoir personnel"},
            {"id": "6F8LB4UUKHs", "titre": "CHAKRA DU CŒUR : S’ouvrir à l’AMOUR et transformer ses relations"},
            {"id": "rf8iyYFbJXs", "titre": "CHAKRA DE LA GORGE : Le débloquer et s'exprimer sans crainte"},
            {"id": "2SPH5DipquY", "titre": "Ouvrir le Chakra du Troisième Œil pour Débloquer Votre Intuition"},
            {"id": "xCwrKiuMwLs", "titre": "CHAKRA COURONNE : Les secrets pour une spiritualité plus profonde !"}
        ]
    },
    "Cédric Michel": {
        "🌞 Méditations du matin & pleine conscience": [
            {"id": "MJ8m10XAf6Q", "titre": "Affirmations positives ANTI STRESS"},
            {"id": "vtGTn2uMevY", "titre": "Méditation du MATIN (et du soir) sur la GRATITUDE"},
            {"id": "pVeE6I_swK0", "titre": "Méditation de pleine conscience"},
            {"id": "kvTXjjRLJts", "titre": "Séance d'affirmations positives du matin"},
            {"id": "Xd8WWrR3L2g", "titre": "Méditation Flash 1 min pour reconnecter au MOMENT PRESENT"},
            {"id": "HdW4eVhZF4g", "titre": "Méditation de pleine conscience du LAC"},
            {"id": "T6VJVRmqVJ8", "titre": "10 min de Calme et de Pleine conscience"},
            {"id": "dNT9sn2GtYs", "titre": "Méditation du MATIN avec 10 affirmations positives"},
            {"id": "5HX3la6aa8I", "titre": "Méditation du matin : Visualisation facile pour une journée parfaite"}
        ],
        "🧘 Méditations quotidiennes & anti-stress": [
            {"id": "rMmPhkNQIF8", "titre": "Replay méditation"},
            {"id": "I8HyAv7E_tg", "titre": "Méditation : Ton esprit est en surcharge ?"},
            {"id": "4M1h-iNt3TQ", "titre": "20 min de Méditation de lâcher prise"},
            {"id": "hmveYa-D-bg", "titre": "Méditation Scan Corporel : Pleine conscience"},
            {"id": "O4Fd_4Il-NI", "titre": "Méditation de lâcher prise"},
            {"id": "hNsb7L7HljY", "titre": "Méditez pour rencontrer votre SAGE INTERIEUR"},
            {"id": "SQS2rddCkew", "titre": "Méditation de Pleine conscience pour réduire stress et anxiété"},
            {"id": "XBomLKM3gN0", "titre": "Méditation chuchotée : les vacances mentales"},
            {"id": "H3CIDQuU6ug", "titre": "Méditation PROGRAMMER TON ESPRIT (avant que le monde le fasse)"}
        ],
        "🧘‍♀️ Méditations du soir": [
            {"id": "VAc7sjhxUPc", "titre": "Méditation guidée sur le lâcher prise - Relaxation Profonde"},
            {"id": "DXLxMzrHQjE", "titre": "Méditation : Lâcher la pression : Votre refuge de paix intérieur"},
            {"id": "_1JR7oscBtg", "titre": "Méditation du soir 10 min pour s'endormir profondément"},
            {"id": "_A9wrmjNYek", "titre": "Méditation : Sommeil profond et réparateur"},
            {"id": "8WUvmEf5n_8", "titre": "Méditation : Bien dormir le soir"},
            {"id": "XVxE-5IEBg8", "titre": "Méditation de relaxation et de lâcher prise"}
        ],
        "🌿 Autres": [
            {"id": "PL0cxOofups", "titre": "Séance d'hypnose pour lâcher prise"},
            {"id": "w5LM9UjS-uA", "titre": "Voilà pourquoi tu n'arrives pas à lâcher prise"},
            {"id": "zhLhyuBWf6U", "titre": "Vous méditez mal sans le savoir"},
            {"id": "qxcMxPEWvyA", "titre": "528Hz musique de nettoyage énergétique - Lâcher prise"}
        ]
    },
    "Marie qui te souffle tes maux": {
        "🔮 Guidance": [
            {"id": "xZlml57ndos", "titre": "Être fière de soi, remplir sa coupe"},
            {"id": "nS0tlAs2jtY", "titre": "Positionne toi face au conflit, prendre sa place."},
            {"id": "ys7ri9EerdY", "titre": "Reprendre son pouvoir créateur et donner du sens à ce que l’on fait."},
            {"id": "1X-5REg7jFg", "titre": "Un week-end sous introspection. L idée est de se poser."},
            {"id": "DndF9Ymzp6w", "titre": "Le résultat n’est pas le plus important"},
            {"id": "GpzDSi3sXgM", "titre": "Le syndrome de l’imposteur dans l’arbre, loyauté familiale."},
            {"id": "QW4yIALEJNg", "titre": "À quelle loyauté invisible obéis-tu sans même t’en rendre compte ?"},
            {"id": "cHRIaxTtgaU", "titre": "Guidance lion, bélier, sagittaire, août 2026."}
        ]
    },
    "Benoit Sanglier": {
        "🌀 Hypnose": [
            {"id": "jVBXYWf2Puw", "titre": "6 étapes pour devenir magnétique"},
            {"id": "KOQNDdgFz7Y", "titre": "Te libérer du regard des autres & activer la confiance en soi"},
            {"id": "YRKFAkyA3vs", "titre": "Manifeste tes rêves"},
            {"id": "0kvZQPeQpcI", "titre": "Libère-toi du perfectionnisme"},
            {"id": "Gty1TUTjomQ", "titre": "Libère ton potentiel"},
            {"id": "HvNrqerhNrs", "titre": "Comment activer une confiance en soi inébranlable"},
            {"id": "Nn_Ic9lyJPw", "titre": "Comment arrêter d'avoir peur du regard des autres"},
            {"id": "IjWrFBtsV_s", "titre": "Comment te sentir enfin légitime et avancer sans attendre la permission des autres"}
        ]
    },
    "Ambre Kouadio": {
        "🌱 Développement personnel": [
            {"id": "hSclgf972U", "titre": "Besoin d'être différente ?"},
            {"id": "6FgSNbf0DY", "titre": "Comment savoir si tu es sur le bon chemin ?"},
            {"id": "1xeTaKDpbrA", "titre": "Pourquoi tu abandonnes toujours avant la fin ?"},
            {"id": "Tnv42qmbBK8", "titre": "Râler : l'habitude toxique qui bloque ton bonheur."},
            {"id": "pnFxK5xtNGQ", "titre": "Schémas amoureux répétitifs : comment ton passé choisit tes partenaires."},
            {"id": "0FYCo9rXM-E", "titre": "Pourquoi le pardon forcé peut rendre malade."},
            {"id": "o1Fh-5mS_u4", "titre": "Ce que ton intérieur révèle de tes blocages invisibles."},
            {"id": "821BPxXRLvw", "titre": "Pourquoi accumuler des formations bloque ton succès."},
            {"id": "CXUrmBZTl9I", "titre": "Ta posture dénonce ton histoire"},
            {"id": "MeRjDv1qERE", "titre": "Pourquoi tu stagnes?"},
            {"id": "4G9DL8IlRQM", "titre": "Procrastination : et si tu avais peur de réussir?"},
            {"id": "Qom5EkQ78sI", "titre": "L'argent te fait culpabiliser ?"},
            {"id": "9Q5pxwaTb_k", "titre": "Malade dès que tu te reposes ?"},
            {"id": "pP4PmY6Bjb0", "titre": "Disputes en boucle ?"},
            {"id": "U-VITwXGPa4", "titre": "Dis oui quand ton corps dis non."},
            {"id": "swoSCECRujA", "titre": "Tu bloques dans ta vie ?"},
            {"id": "TuDzK3Bl_Wk", "titre": "Mâchoires serrées : Ce que tu n'oses pas dire"},
            {"id": "EVHhBio2Xqg", "titre": "Tu as peur de vieillir ?"},
            {"id": "WNSvlqqA6KY", "titre": "Surveille tes pensées"},
            {"id": "9qiO-545JKk", "titre": "La culpabilité est un conditionnement"}
        ],
        "⚡ La minute énergie": [
            {"id": "0ZwmBq4ULmo", "titre": "Fatigue chronique : pourquoi le repos ne suffit plus quand on est une éponge énergétique."},
            {"id": "6FFLM-npMKA", "titre": "Pourquoi tu te réveilles à 3h du matin ?"},
            {"id": "PlPqHjNmNcc", "titre": "Finances et spiritualité : pourquoi ton rapport au plaisir dicte ton abondance"},
            {"id": "xboeFxD2JUk", "titre": "Comment les secrets de famille impactent ton corps."},
            {"id": "YEFoSJth_R0", "titre": "Comment identifier et expulser les parasites du bas-astral."},
            {"id": "vVOp9-32wtw", "titre": "Comment nettoyer les mémoires des objets d'occasion."},
            {"id": "BwL5Fm_pCwk", "titre": "Pourquoi ton enfant est ton plus grand guide énergétique."},
            {"id": "TL_mcTLNCwM", "titre": "Le jeûne de parole"},
            {"id": "Sajg7EcVDlg", "titre": "Peur de briller"},
            {"id": "QND7q9xDH9k", "titre": "Cheveux qui tombent : La fuite de ton pouvoir"},
            {"id": "KMnIY_J7g3E", "titre": "Sucre : Ta faim est un mensonge"},
            {"id": "IooZYgQIE6s", "titre": "La guerre de l'argent et de la gentillesse"},
            {"id": "QM-fXMoXOTM", "titre": "En décalage ? Et si c'était ta plus grande force ?"},
            {"id": "S3EUlhRIUqM", "titre": "Ta maison t'épuise ?"},
            {"id": "y8ReWWb4J4M", "titre": "Tu travailles trop pour ce résultat ?"},
            {"id": "iTbyUIYvgkk", "titre": "Ne déteste pas ton anniversaire"},
            {"id": "C-defSZBCM4", "titre": "Le piège de la spiritualité"},
            {"id": "uww114GZT_o", "titre": "Tu es reliée au monde énergétique"},
            {"id": "o-UUs4lsVX4", "titre": "Plus tu forces, plus ça bloque !"},
            {"id": "yf2i8uP60pw", "titre": "Il manque quelque chose à ta vie ?"}
        ]
    },
    "Luc Bodin": {
        "🦋 Évolution personnelle": [
            {"id": "ikaRmSQ9ICU", "titre": "Changer de vie pour suivre son chemin, c’est possible"},
            {"id": "dz5nC3VYveE", "titre": "Le symbole Lémurien pour éliminer ses blocages psychologiques"},
            {"id": "cIWdErlnLNk", "titre": "Entretien : Développez vos talents subtils"},
            {"id": "IDtTNcXxeq0", "titre": "Méditation - Renouer avec son enfant intérieur"},
            {"id": "GgwbTIpx51I", "titre": "Tous ensemble rêvons le monde de demain"},
            {"id": "bCrNM1DgyUk", "titre": "Comment trouver son chemin de vie ?"},
            {"id": "ra8-2tLoLa0", "titre": "Ensemble changeons le monde"},
            {"id": "QrpKf9C2wYA", "titre": "Le monde d’après"},
            {"id": "5NJOJigZzMg", "titre": "Comment élever son niveau vibratoire ?"},
            {"id": "rZnW0oBBhcc", "titre": "Les 3 clés de l’ascension"},
            {"id": "GympbBSsTqs", "titre": "Comment contacter ses guides et les êtres de lumière ?"},
            {"id": "JZTXCngiO9c", "titre": "La crise sanitaire, un enjeu planétaire pour l'humanité"},
            {"id": "Am9mgrSyC1A", "titre": "Notre cœur connait notre chemin de vie"},
            {"id": "s1V2y3MJ6kU", "titre": "Soigner avec l'énergie - Les thérapies quantiques et Psycho énergétiques"},
            {"id": "1V9FUAunY1E", "titre": "Apprendre à réaliser la Prière du feu"},
            {"id": "MxgICsQXBRM", "titre": "Petits messages pour vous"},
            {"id": "OcH2T7Mnk5k", "titre": "Le pouvoir extraordinaire des sons"}
        ],
        "🫀 Santé": [
            {"id": "jsyiZAxBGck", "titre": "La méthode Aora pour soulager ses problèmes de santé"},
            {"id": "TuPQV11Tsfc", "titre": "La méthode Aora"},
            {"id": "eN7vmxCoxnw", "titre": "Comment équilibrer sa flore intestinale pour une bonne santé"},
            {"id": "eo5U_ZLmB8E", "titre": "Apprendre à relancer son système immunitaire"},
            {"id": "pRsI8T8G1BQ", "titre": "Qu’est qu’une alimentation saine et équilibrée ?"},
            {"id": "vnMj9ogT4hs", "titre": "Le traitement holistique du cancer"},
            {"id": "6452EJnYBTQ", "titre": "La normalisation des cellules cancéreuses"},
            {"id": "Z4d-KzrxCpQ", "titre": "Cancer, les chemins de la guérison"},
            {"id": "LLJRQ5vGdsc", "titre": "Une conférence de Luc Bodin sur l’épigénétique"},
            {"id": "y1EDr4NYgtU", "titre": "Sortir du stress pour vivre libre"},
            {"id": "uz0CVrCiMgA", "titre": "La médecine de demain"},
            {"id": "aoLxvENQWXM", "titre": "Tout savoir sur la médecine spirituelle"},
            {"id": "WQMF5kptCRU", "titre": "Surmonter la Fibromyalgie"},
            {"id": "cmQSRTHFxPk", "titre": "Restez Jeune et en Bonne Santé"},
            {"id": "v92ysjylQp8", "titre": "Comment remonter vos défenses immunitaires ?"},
            {"id": "urZc6CwvkOE", "titre": "La médecine spirituelle - Soigner l’âme pour guérir le corps"},
            {"id": "hL0yMmKmXLQ", "titre": "Comment utiliser l’eau pour élever son niveau vibratoire ?"},
            {"id": "6dTz30Z1LEk", "titre": "Symboliques des maladies"},
            {"id": "qDTEW3wg8UU", "titre": "Boostez vos mitochondries pour votre santé et votre longévité."}
        ],
        "🎙️ Interview": [
            {"id": "hmNoyBo2-s4", "titre": "Le grand changement Vibratoire de la Terre"},
            {"id": "jR0nBvGud28", "titre": "Les entités, les connaître pour les comprendre"},
            {"id": "qBa_NKSdUq4", "titre": "Entre chaos et lumière, le grand basculement"},
            {"id": "Fj6EbxraOkA", "titre": "Soigner les animaux avec des soins énergétiques"},
            {"id": "OryZFRy-C0o", "titre": "Forces invisibles, savoirs occultés et réveil des consciences"},
            {"id": "D_iQirDeNBo", "titre": "Des soins énergétiques pour le bien-être animal"},
            {"id": "8BnnEwTLr1g", "titre": "Vers un futur lumineux : santé, conscience et transformation planétaire"},
            {"id": "3ZkTBboQ41o", "titre": "Dépasser vos conditionnements pour retrouver votre lumière"},
            {"id": "GjQqL4aIeMU", "titre": "Une transition spirituelle décisive pour l’humanité"},
            {"id": "ISV_pOjrOOY", "titre": "Les clés d’une spiritualité épanouie"},
            {"id": "82GLVDlvqp4", "titre": "la Mort du Pape, la Prophétie de Malachie et l’Apocalypse"},
            {"id": "P-J79q7ZqJY", "titre": "La chute des maitres : La fiction rejoindrait-elle la réalité ?"},
            {"id": "p2BxQJQWjdE", "titre": "Harmonisation énergétique, auto-guérison et santé"},
            {"id": "gG76cs2PG8U", "titre": "Le grand pouvoir de l’esprit sur le corps"},
            {"id": "vRz5fNZLYpA", "titre": "Libérez votre pouvoir guérisseur et transformez votre vie"},
            {"id": "KwQb1G8cjds", "titre": "Mini-Sommet sur les Nouveaux Enfants"},
            {"id": "MatoFV-JQEk", "titre": "L'éveil de la conscience"},
            {"id": "pP42iKbKCqI", "titre": "Stress et Anxiété"},
            {"id": "A0tR0CwApzo", "titre": "Comment passer l’hiver en bonne santé ?"},
            {"id": "RrsGGqsCMT4", "titre": "Comment soigner les animaux avec l’énergie ?"},
            {"id": "x_M6cw73JM0", "titre": "Comment développer la puissance de notre pouvoir guérisseur ?"},
            {"id": "Fw1c712T8mc", "titre": "Développez votre pouvoir guérisseur"},
            {"id": "qWwaMlwNRPQ", "titre": "Les dessous des cartes vus par La chute des maitres"},
            {"id": "k59i5-laots", "titre": "Comment soigner les animaux avec l’énergie ?"},
            {"id": "tbM683xn8Js", "titre": "La voie du milieu, entre ombre et lumière"},
            {"id": "4yXkQGjd_KU", "titre": "Une pensée positive dans le monde actuel"},
            {"id": "mBtDGeTIPBk", "titre": "Un message d’espoir dans le chaos actuel"},
            {"id": "KbmGYU_SiW8", "titre": "L’homme multidimensionnel"},
            {"id": "e6TdoVI27Wc", "titre": "Les voies menant à la guérison du corps et de l’esprit"},
            {"id": "wdvxOHiHxl4", "titre": "Le grand Reseat : déprogrammation & reprogrammation"},
            {"id": "HaJrpcXwd5Y", "titre": "Mon expérience de la chambre à Tachyons"},
            {"id": "LjQLxn6HhU4", "titre": "Sortir du stress pour vivre libre"},
            {"id": "iB9KJ2LyMcI", "titre": "De la sagesse polynésienne à la mission de vie"},
            {"id": "Gx61VytL-ZE", "titre": "Comment faire évoluer la transition que nous vivons, vers un monde de paix et de lumière ?"},
            {"id": "CsPgpyUuQl4", "titre": "Les champs du possible"},
            {"id": "Ndo9Kl770cY", "titre": "Conscience vibratoire et Spiritualité (1ère partie)"},
            {"id": "RlWzAbG5nN8", "titre": "Conscience vibratoire et Spiritualité (2ème partie)"},
            {"id": "iBwZElrgQKE", "titre": "Prévenir les infections saisonnières et récidivantes"},
            {"id": "esXEa088Hfc", "titre": "Un soin énergétique"},
            {"id": "dYsl_O7_jco", "titre": "La médecine spirituelle pour soigner le corps et l’esprit"},
            {"id": "O72RLy-Wjlc", "titre": "Les corps énergétiques, les chakras, la kundalini, la corde d’argent et la circulation énergétique"},
            {"id": "Kp1Y0yt8TPw", "titre": "Savoir demander pour recevoir"},
            {"id": "MJKFyaUf1vk", "titre": "Apprendre à développer son magnétisme"},
            {"id": "cN-jzuBAhA4", "titre": "Comprendre et utiliser les synchronicités"},
            {"id": "TsK8kL-Twzo", "titre": "La puissance des pierres au service de notre bien-être"},
            {"id": "KUyuGwfLmQM", "titre": "Les soins énergétiques pour les animaux"},
            {"id": "ObzdgM9gITg", "titre": "Les changements en cours et comment les gérer dans la sérénité"},
            {"id": "SZbqxQNJr64", "titre": "Le Manuel de soins énergétiques pour les animaux"},
            {"id": "Q6lVtBvTwPc", "titre": "La vibration de la Terre en pleine évolution"},
            {"id": "rPLWINBY47g", "titre": "Des soins énergétiques pour les animaux"},
            {"id": "h6Hqhj0rmqg", "titre": "Les limites de la réalité et dévoile les secrets de l’harmonie intérieure"},
            {"id": "UvnvcgCXKg", "titre": "Déprogrammation et entrée dans le nouveau monde"},
            {"id": "7uMF7aXFDRc", "titre": "Du sens symbolique des maladies à la médecine holistique"},
            {"id": "Fq8ZfbaDW54", "titre": "Rituels ancestraux : booster votre santé !"},
            {"id": "c384J7YgnTU", "titre": "Les extraordinaires bienfaits de la bromélaïne"},
            {"id": "zG9j5FrLxt4", "titre": "Pour notre avenir, déprogrammons-nous"},
            {"id": "W7smJWlXpoM", "titre": "Comment se recharger en énergie"},
            {"id": "qOd8cHmKAqs", "titre": "Le pardon pour débloquer les conflits et avancer dans sa vie"},
            {"id": "llRpuvC41S0", "titre": "Apprendre à harmoniser ses corps énergétiques"},
            {"id": "nTvNb0cRCM", "titre": "L’arrivée du nouveau monde de la 5e dimension"},
            {"id": "-_SBvxZ14r4", "titre": "Développer la force de sa pensée"},
            {"id": "tVvHDtnte7c", "titre": "Surmonter rapidement la fatigue"},
            {"id": "O4wprVA8HVk", "titre": "Nettoyage et purification au gros sel"},
            {"id": "Zq5t9ptLd_4", "titre": "Nettoyage et protection énergétiques des personnes et des lieux"},
            {"id": "eU8QIbRxNXc", "titre": "Trouver l'amour en soi pour élever sa vibration"},
            {"id": "WNC17gQfwak", "titre": "Une clé pour incarner la paix et la nouvelle Terre"},
            {"id": "mNeDpRZagW4", "titre": "Ensemble pour incarner la paix et la nouvelle Terre"},
            {"id": "bfGThp2prMM", "titre": "Ayurveda et Soins Énergétiques"},
            {"id": "48QltilOnLw", "titre": "Surmonter son stress et ses émotions avec les thérapies holistiques"},
            {"id": "dbC1tT6RdJQ", "titre": "Une sagesse ancestrale provenant de Lémurie"},
            {"id": "Wdx9mBxuzy0", "titre": "L'élévation du taux vibratoire de la Terre"},
            {"id": "SAFmhZysC1Q", "titre": "Rencontre sur la voix de l’âme"}
        ],
        "💫 Le portail de lumière": [
            {"id": "p5rizau4PIM", "titre": "La conscience, clé de notre liberté"},
            {"id": "AxyD8eRknqc", "titre": "Alliance des Consciences - pour éveiller votre pouvoir guérisseur"},
            {"id": "cIDMZUAYGBA", "titre": "Le Chaos avant le renouveau"},
            {"id": "1bmpQJMJ4Wc", "titre": "Quel avenir pour l’humanité ?"},
            {"id": "hhO88Kbm2-8", "titre": "Le protocole d’ajustement rapide"},
            {"id": "LBRa-AlKjss", "titre": "Le grand réajustement intérieur en cours"},
            {"id": "OqOLgKm8l4U", "titre": "Les prochains mois : vers un basculement silencieux ?"},
            {"id": "CsxsPKW2EpM", "titre": "Le monde change… mais l’être humain suit-il vraiment ?"},
            {"id": "_AW8bmzg2t0", "titre": "Changez maintenant ou subissez demain."},
            {"id": "nML7_-Dl0hg", "titre": "Le temps est venu d’éveiller notre Lumière"},
            {"id": "IXKDuMPTYTk", "titre": "L’ascension vibratoire n’attend plus que l’humanité"},
            {"id": "PuB_GarPhc", "titre": "Comment préserver sa lumière dans un monde anxiogène"},
            {"id": "lbncUIAlkG8", "titre": "Vibrez dans la lumière malgré les ombres"},
            {"id": "oOUCbN76C58", "titre": "Planète en mutation, Esprits sous contrôle"},
            {"id": "JB1bhD7v5h4", "titre": "Un Monde en Transition : Crises, Nettoyage et Renaissance"},
            {"id": "Hb2y9yuVe20", "titre": "Tout s’accélère. L’heure du changement approche."},
            {"id": "1pNxpVveN20", "titre": "Tous ensemble rêvons le monde de demain"},
            {"id": "7rqotlG3-Q8", "titre": "Pourquoi la vie n’est pas un long fleuve tranquille ?"},
            {"id": "EjNFrc_rAhw", "titre": "Perturbation du temps, conflits et élévation vers une nouvelle conscience"},
            {"id": "veSIVfIVcfA", "titre": "Préparons la paix et non la guerre"},
            {"id": "jNvF9o-ineE", "titre": "Sur le plan subtil, une nouvelle étape est en gestation. Il faut nous y préparer."},
            {"id": "1yX9xDtl1AI", "titre": "Le Taux Vibratoire de la Terre s’élève toujours et des portails de lumière s’ouvrent"},
            {"id": "qKQwttE8fyU", "titre": "Pourquoi et comment élever son niveau vibratoire ? Comment le mesurer ?"},
            {"id": "WPruVYZMss0", "titre": "Perturbations en vue… mais la lumière brille toujours"},
            {"id": "x6cv3OKOYIc", "titre": "La nuit noire de l’âme"},
            {"id": "rAqOgStbURs", "titre": "La Terre a besoin de votre lumière"},
            {"id": "l5jjuINWoRo", "titre": "La Terre dernier refuge des forces obscures"},
            {"id": "DssXpunACsA", "titre": "Les énergies repartent à la hausse depuis le portail du 888"},
            {"id": "eughV1t_BUg", "titre": "Explications sur le Taux Vibratoire de la Terre (TVT)"},
            {"id": "q5MeQtqj4W8", "titre": "Beaucoup de nocivités subtiles se développent actuellement sur Terre"},
            {"id": "_m78ILKOUgE", "titre": "Brouillard cérébral ou Brouillage cérébral ?"},
            {"id": "86jpp0bqFCE", "titre": "Croyez en vous"},
            {"id": "f8dXsJzMvQQ", "titre": "Ça bouge dans le ciel et dans les énergies. Qu’est-ce que le brouillard cérébral ?"},
            {"id": "e3fkIYncIeA", "titre": "La situation actuelle dans l’énergie"},
            {"id": "GDFDR1bPs3M", "titre": "La médecine intégrative (et spirituelle)"},
            {"id": "mEV3NRtVedg", "titre": "La résonance de Schumann s’affole. Que se passe-t-il ?"},
            {"id": "pATLAEM_fqw", "titre": "Suivre la situation vibratoire et se préparer au changement"},
            {"id": "Q0PECyb3CWY", "titre": "Comment évoluent les énergies ?"},
            {"id": "cAXc0uFv4Ic", "titre": "Des nouvelles concernant le niveau vibratoire de la Terre et ses conséquences"},
            {"id": "Z-yVIV6yoVM", "titre": "Ombre et Lumière"},
            {"id": "x5zwnGMdqsc", "titre": "Que se passe-t-il au niveau énergétique et au niveau du taux vibratoire de la Terre ?"},
            {"id": "SeteiWxbek4", "titre": "Comment recevoir les nouvelles énergies ?"},
            {"id": "a3t0qkHkgmU", "titre": "Le taux vibratoire de la Terre - Pourquoi augmente-t-il autant ? Quels effets sur nous ?"},
            {"id": "Ob73a1ASpyo", "titre": "De nouvelles énergies arrivent sur terre"}
        ],
        "🧘 Méditations": [
            {"id": "wTsZijsdmrI", "titre": "Grande méditation de soutien aux victimes des incendies, aux pompiers et à la Terre"},
            {"id": "cWNd82jqVi0", "titre": "Méditation : Les bâtisseurs du Nouveau Monde"},
            {"id": "cHWwzcQH488", "titre": "Méditation de déprogrammation - pour briser vos chaînes invisibles"},
            {"id": "voq5BJkrPII", "titre": "Méditation pour l’amour"},
            {"id": "g1QhzwNMarw", "titre": "Méditation pour se détendre et se relaxer"},
            {"id": "9iDt89G9RMI", "titre": "Affirmations positives méditatives pour l’estime de soi"},
            {"id": "GFK4L6fZbIM", "titre": "Méditation et Soin Énergétique Mondial pour tous les êtres en souffrance"},
            {"id": "1zFC3Qlz4cs", "titre": "Une méditation guidée pour apaiser votre anxiété et retrouver votre paix intérieure"},
            {"id": "y9SKGV8RXq4", "titre": "Méditation pour rencontrer son double intérieur"},
            {"id": "JRt-ZpWU-jc", "titre": "Méditation : Tous unis dans l’amour Divin"},
            {"id": "Ug6zj-cBe6w", "titre": "Méditation : Réveillez votre Étincelle Divine"},
            {"id": "mEKrTVDcxzQ", "titre": "Méditation du Portail de Lumière"},
            {"id": "31tgtTVFde8", "titre": "Méditation - Nettoyage et élévation de son être avec le Portail de Lumière"},
            {"id": "hOarHnmltxI", "titre": "Méditation avec les nouvelles énergies"},
            {"id": "QbxzsgHNnYQ", "titre": "Méditation transgénérationnelle"},
            {"id": "HBlOJmlRZYg", "titre": "Méditation à la rencontre de votre ÊTRE SUPÉRIEUR"},
            {"id": "zwM6j5SLKQo", "titre": "Méditation pour vous connecter au champ d’énergies informées"},
            {"id": "IXUTjhGBcQ0", "titre": "Méditation pour rencontrer son être intérieur et obtenir des réponses sur ses problèmes, sa mission"},
            {"id": "YB_5LCMiMeE", "titre": "Méditation d’amour pour soi et pour l’humanité"},
            {"id": "5Rr9RmBpElg", "titre": "Une méditation pour la paix dans le monde"},
            {"id": "X-P6QXkjBps", "titre": "Une méditation d’amour pour l’humanité"},
            {"id": "Ssa92UbfbI0", "titre": "Une méditation d’amour pour soi"},
            {"id": "fbbXErASPGU", "titre": "Une méditation pour maintenir l’harmonie de son être"},
            {"id": "J7klAB4bIgA", "titre": "Une méditation pour vivre l’amour de soi et… de l’humanité"},
            {"id": "AUSL5nS2f3Y", "titre": "Une méditation pour développer la joie, le bonheur et l’harmonie"},
            {"id": "xjTns7ft6Hg", "titre": "La grande méditation cosmique"},
            {"id": "QRKBPe-Tq0I", "titre": "Méditation pour retrouver harmonie, équilibre, bien-être et joie"},
            {"id": "GaJ7Aw_IYVQ", "titre": "Méditation pour la Paix dans le Monde"},
            {"id": "LKlOiFvZVD4", "titre": "Méditation pour développer la joie et le bonheur en vous et autour de vous"},
            {"id": "3jcngllTjSc", "titre": "Méditation pour se baigner dans la Source Divine"},
            {"id": "LOTBoPxsFdU", "titre": "Une méditation guidée pour remercier les Êtres de lumière et la Divine Source"},
            {"id": "u-QIqixV05o", "titre": "Une méditation guidée pour que vous échangiez avec votre être intérieur"},
            {"id": "wh7UKIy5DoU", "titre": "Méditation pour envoyer de l’amour à soi-même et à l’humanité"},
            {"id": "K0_2mNNTsIU", "titre": "Méditation guidée pour trouver son alignement"},
            {"id": "QMRHePYjrc4", "titre": "Une méditation guidée pour se connecter à la Source"},
            {"id": "_PvS8WIZL9k", "titre": "Une méditation guidée pour purifier votre être"},
            {"id": "rb2udYidc8g", "titre": "Une méditation courte pour envoyer de l’amour autour de soi"},
            {"id": "lLgAjF5vr1E", "titre": "Méditation guidée pour rencontrer votre être de lumière"},
            {"id": "anDpnLICXPs", "titre": "Méditation guidée pour rencontrer ses Guides"},
            {"id": "AF1HxeVUagY", "titre": "Méditation guidée sur l’amour de soi"},
            {"id": "rsK1RCX41ig", "titre": "Méditation guidée – Recevoir les énergies pour développer votre vitalité"},
            {"id": "HJ9Y_2m8Slg", "titre": "Une méditation pour l’amour universel"},
            {"id": "H4ZVrPs1iZ4", "titre": "Une méditation pour développer sa lumière intérieure"},
            {"id": "WkZ9p3LwUNQ", "titre": "Méditation pour que s'éteignent les Mégafeux et pour soutenir les Pompiers et les Habitants"},
            {"id": "B8On4sED_qo", "titre": "Méditation Guidée pour la Paix dans le Monde"},
            {"id": "RmHXmlADfvU", "titre": "Méditation pour le convoi de la liberté"},
            {"id": "1sOCxLeFHrQ", "titre": "Comment méditer ?"},
            {"id": "w3zod9SvOD4", "titre": "Première méditation collective sur l’amour de soi et de l’humanité"},
            {"id": "U2JoxyeGd5Y", "titre": "Deuxième méditation collective pour l’amour de soi et de l’humanité"},
            {"id": "mntMickumYA", "titre": "Troisième méditation collective pour l’amour de soi et de l’humanité"}
        ],
        "💫 Soin énergétique": [
            {"id": "isTs5zuKYgI", "titre": "Les soins énergétiques, comment ça marche ?"},
            {"id": "fMOzfIXLhdQ", "titre": "Comprendre les soins énergétiques"},
            {"id": "17SqMLOMCR4", "titre": "Venez découvrir les soins énergétiques"},
            {"id": "z0PqveiGIAM", "titre": "Indications et techniques des soins énergétiques"},
            {"id": "H_yEGTgT-mc", "titre": "Soigner nos problèmes de santé avec les soins énergétiques"},
            {"id": "reVjznIDmxo", "titre": "Comment le mouvement primordial peut transformer votre vie"},
            {"id": "Jz8o6ML5178", "titre": "Comment voir l’aura ?"},
            {"id": "s5HHH5uqhpA", "titre": "Affirmations positives effet hypnose AUGMENTER SON NIVEAU VIBRATOIRE"}
        ]
    }
}